version: "2"

services:
  app:
    container_name: "app"
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console
    links:
         - "db:database"

  db:
    container_name: "db"
    image: "mysql:latest"
    environment:
      - MYSQL_DATABASE=restaurant
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=supersecret
    volumes:
      - ./workdir/db/init/:/docker-entrypoint-initdb.d/ # init database
      - ./workdir/db/data/:/var/lib/mysql/              # data storage
    ports:
      - "3306:3306"

networks:
    default:
        driver: bridge
